import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider, SignedIn } from '@clerk/nextjs'
import AddNote from "@/components/AddNote";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}

          <SignedIn>
            <AddNote />
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}
